### PR TITLE
compatibility(streams): support OnNextBatchAsync

### LINKED ISSUE #107: TestStream OnNextBatchAsync
Are there any plans to support OnNextBatchAsync in TestStream?
https://github.com/OrleansContrib/OrleansTestKit/blob/f279cfc3d81dc64a30425cc18280c7bd3558d546/src/OrleansTestKit/Streams/TestStream.cs#L94

Currently, we have been forced to switch to using OnNextAsync to avoid failing unit tests.  This can have undesired performance / cost implications depending on the actual stream implementation used for the release.

### PR DESCRIPTION
**Pull request by michaeltdaniels**
closes #107

### CODE REVIEW

File: src/OrleansTestKit/Streams/TestStream.cs [hunk 1]
```diff
@@ -91,8 +91,17 @@ public Task OnNextAsync(T item, StreamSequenceToken token = null)
...
-            throw new NotImplementedException();
+        public async Task OnNextBatchAsync(IEnumerable<T> batch, StreamSequenceToken token = null)
+        {
+            if (batch == null)
+            {
+                throw new ArgumentNullException(nameof(batch));
+            }
+            foreach (var item in batch)
+            {
+                await OnNextAsync(item, token).ConfigureAwait(false);
```
Comment (seniorquico) [inline src/OrleansTestKit/Streams/TestStream.cs:102]: If an error occurs processing an item, the for loop will terminate. Is that desired/expected?

Comment (michaeltdaniels) [reply src/OrleansTestKit/Streams/TestStream.cs]: I added handling / rethrowing an AggregateException to allow all messages to be sent, but still bubble up any exceptions.

Comment (seniorquico) [reply src/OrleansTestKit/Streams/TestStream.cs]: That sounds like a nice approach. Is that the same behavior as Orleans?

Comment (michaeltdaniels) [reply src/OrleansTestKit/Streams/TestStream.cs]: It depends on which stream provider you're using.  We use SQS, for instance.  Since the message is pushed off to an out-of-process message queue, an exception from the subscriber wouldn't bubble up to the publisher.  Simple Message Stream Provider, on the other hand, would propagate the exception back to the caller for OnNextAsync.  SMS doesn't currently support OnNextBatchAsync https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Streaming/SimpleMessageStream/SimpleMessageStreamProducer.cs#L121.

**Review by seniorquico — APPROVED** [review]

**Comment by michaeltdaniels** [comment]
@seniorquico - can you approve the workflow?

**Comment by seniorquico** [comment]
> @seniorquico - can you approve the workflow?

I already approved it, but the GitHub mobile app is blocking the merge. 😕

I'll get to it when I have access from a computer.

**Comment by michaeltdaniels** [comment]
@seniorquico - any update?

**Comment by seniorquico** [comment]
@michaeltdaniels Released to NuGet as 3.1.5.
